export const photos = [
  {
    id: "photo-01",
    src: "/images/portfolio/photo-01-mongkrang-expedition.jpg",
    title: "Cozmeed Expedition",
    caption: "Videographer — PT. Cozmeed Network International",
    meta: "Mongkrang, Tawangmangu · Dec 2024",
  },
  {
    id: "photo-02",
    src: "/images/portfolio/photo-02-stage-photography.jpg",
    title: "Stage Photography",
    caption: "Live concert and stage documentation",
    meta: "Various venues",
  },
  {
    id: "photo-03",
    src: "/images/portfolio/photo-03-campaign-graduation.jpg",
    title: "Campaign & Ceremony",
    caption: "Official campaign, graduation and engagement moments",
    meta: "Karanganyar, Central Java",
  },
  {
    id: "photo-04",
    src: "/images/portfolio/photo-04-event-documentation.jpg",
    title: "Solo Market Fest",
    caption: "Full event documentation",
    meta: "Solo, Central Java",
  },
  {
    id: "photo-05",
    src: "/images/portfolio/photo-05-film-projects.jpg",
    title: "Film Projects",
    caption: "Documentary and short film production stills",
    meta: "2022 – 2023",
  },
  {
    id: "photo-06",
    src: "/images/portfolio/photo-06-creative-design.jpg",
    title: "Abiyoso Merchandise",
    caption: "Product photography and creative catalog design",
    meta: "2022 – 2024",
  },
  {
    id: "photo-07",
    src: "/images/portfolio/photo-07-drone-social.jpg",
    title: "Drone & Social Media",
    caption: "Aerial cinematography and social media management",
    meta: "Multiple locations",
  },
];

export const contact = {
  phone: { display: "+62 8985283453", href: "tel:+628985283453" },
  email: { display: "kevinsany12@gmail.com", href: "mailto:kevinsany12@gmail.com" },
  instagram: {
    display: "@kevinsany",
    href: "https://www.instagram.com/kevinsany?utm_source=ig_web_button_share_sheet&igsi=ZDNlZDc0MzIxNw==",
  },
};

export const videos = [
  {
    id: "after-movie-bege-2-stroke",
    title: "AFTER MOVIE BEGE 2 STROKE",
    caption: "",
    meta: "1:41",
    orientation: "horizontal",
    type: "local",
    src: "/videos/horizontal/after-movie-bege-2-stroke.mp4",
    poster: "/videos/posters/after-movie-bege-2-stroke.jpg",
  },
    {
    id: "internal-hari-natal-rumah-presdir-rev-1",
    title: "INTERNAL - HARI NATAL RUMAH PRESDIR Rev 1",
    caption: "",
    meta: "2:01",
    orientation: "horizontal",
    type: "local",
    src: "/videos/horizontal/internal-hari-natal-rumah-presdir-rev-1.mp4",
    poster: "/videos/posters/internal-hari-natal-rumah-presdir-rev-1.jpg",
  },
  {
    id: "asics-rev1",
    title: "ASICS REV1",
    caption: "",
    meta: "1:39",
    orientation: "horizontal",
    type: "local",
    src: "/videos/horizontal/asics-rev1.mp4",
    poster: "/videos/posters/asics-rev1.jpg",
  },
  {
    id: "aftermovie-fantasticmarket",
    title: "AFTERMOVIE FANTASTICMARKET",
    caption: "",
    meta: "1:00",
    orientation: "horizontal",
    type: "local",
    src: "/videos/horizontal/aftermovie-fantasticmarket.mp4",
    poster: "/videos/posters/aftermovie-fantasticmarket.jpg",
  },
  {
    id: "downforlife-at-fantastic-market",
    title: "DOWNFORLIFE AT FANTASTIC MARKET",
    caption: "",
    meta: "1:02",
    orientation: "horizontal",
    type: "local",
    src: "/videos/horizontal/downforlife-at-fantastic-market.mp4",
    poster: "/videos/posters/downforlife-at-fantastic-market.jpg",
  },
  {
    id: "kpu-p-mondokkan",
    title: "KPU P.MONDOKKAN",
    caption: "",
    meta: "0:54",
    orientation: "horizontal",
    type: "local",
    src: "/videos/horizontal/kpu-p-mondokkan.mp4",
    poster: "/videos/posters/kpu-p-mondokkan.jpg",
  },
  {
    id: "kpu-p-plupuh",
    title: "KPU P.PLUPUH",
    caption: "",
    meta: "0:54",
    orientation: "horizontal",
    type: "local",
    src: "/videos/horizontal/kpu-p-plupuh.mp4",
    poster: "/videos/posters/kpu-p-plupuh.jpg",
  },
  {
    id: "landscape",
    title: "LANDSCAPE",
    caption: "",
    meta: "0:28",
    orientation: "horizontal",
    type: "local",
    src: "/videos/horizontal/landscape.mp4",
    poster: "/videos/posters/landscape.jpg",
  },
  {
    id: "riding-the-pasutri-2",
    title: "RIDING THE PASUTRI #2",
    caption: "",
    meta: "0:43",
    orientation: "horizontal",
    type: "local",
    src: "/videos/horizontal/riding-the-pasutri-2.mp4",
    poster: "/videos/posters/riding-the-pasutri-2.jpg",
  },
  {
    id: "riding-the-pasutri-part-1",
    title: "RIDING THE PASUTRI (PART 1)",
    caption: "",
    meta: "2:11",
    orientation: "horizontal",
    type: "local",
    src: "/videos/horizontal/riding-the-pasutri-part-1.mp4",
    poster: "/videos/posters/riding-the-pasutri-part-1.jpg",
  },
  {
    id: "teaser-smf-summer-sale",
    title: "Teaser SMF Summer Sale",
    caption: "",
    meta: "0:33",
    orientation: "horizontal",
    type: "local",
    src: "/videos/horizontal/teaser-smf-summer-sale.mp4",
    poster: "/videos/posters/teaser-smf-summer-sale.jpg",
  },
  {
    id: "baselayer-firefly-02",
    title: "Baselayer Firefly 02",
    caption: "",
    meta: "0:19",
    orientation: "vertical",
    type: "local",
    src: "/videos/vertical/baselayer-firefly-02.mp4",
    poster: "/videos/posters/baselayer-firefly-02.jpg",
  },
  {
    id: "kahf-final-rev",
    title: "KAHF Final Rev",
    caption: "",
    meta: "0:42",
    orientation: "vertical",
    type: "local",
    src: "/videos/vertical/kahf-final-rev.mp4",
    poster: "/videos/posters/kahf-final-rev.jpg",
  },
  {
    id: "rev-xiaomi-watch-tws",
    title: "REV XIAOMI WATCH&TWS",
    caption: "",
    meta: "0:40",
    orientation: "vertical",
    type: "local",
    src: "/videos/vertical/rev-xiaomi-watch-tws.mp4",
    poster: "/videos/posters/rev-xiaomi-watch-tws.jpg",
  },
  {
    id: "salinan-flash-sale-gratis-ongkir-2",
    title: "Salinan FLASH SALE GRATIS ONGKIR 2",
    caption: "",
    meta: "0:10",
    orientation: "vertical",
    type: "local",
    src: "/videos/vertical/salinan-flash-sale-gratis-ongkir-2.mp4",
    poster: "/videos/posters/salinan-flash-sale-gratis-ongkir-2.jpg",
  },
  {
    id: "sendal-cozmeed-malaka",
    title: "Sendal Cozmeed \"Malaka\"",
    caption: "",
    meta: "0:34",
    orientation: "vertical",
    type: "local",
    src: "/videos/vertical/sendal-cozmeed-malaka.mp4",
    poster: "/videos/posters/sendal-cozmeed-malaka.jpg",
  },
  {
    id: "20-ra-jasa-mendoakan",
    title: "20 RA JASA MENDOAKAN",
    caption: "",
    meta: "0:41",
    orientation: "vertical",
    type: "local",
    src: "/videos/vertical/20-ra-jasa-mendoakan.mp4",
    poster: "/videos/posters/20-ra-jasa-mendoakan.jpg",
  },
  {
    id: "episode-1",
    title: "EPISODE 1",
    caption: "",
    meta: "1:24",
    orientation: "vertical",
    type: "local",
    src: "/videos/vertical/episode-1.mp4",
    poster: "/videos/posters/episode-1.jpg",
  },
  {
    id: "episode-1-1",
    title: "EPISODE 1+1",
    caption: "",
    meta: "1:26",
    orientation: "vertical",
    type: "local",
    src: "/videos/vertical/episode-1-1.mp4",
    poster: "/videos/posters/episode-1-1.jpg",
  },
  {
    id: "episode-3",
    title: "EPISODE 3",
    caption: "",
    meta: "1:30",
    orientation: "vertical",
    type: "local",
    src: "/videos/vertical/episode-3.mp4",
    poster: "/videos/posters/episode-3.jpg",
  },
  {
    id: "episode-4",
    title: "EPISODE 4",
    caption: "",
    meta: "1:30",
    orientation: "vertical",
    type: "local",
    src: "/videos/vertical/episode-4.mp4",
    poster: "/videos/posters/episode-4.jpg",
  },

  {
    id: "no-bgm-respati-ardi-1",
    title: "NO BGM Respati Ardi 1",
    caption: "",
    meta: "0:34",
    orientation: "vertical",
    type: "local",
    src: "/videos/vertical/no-bgm-respati-ardi-1.mp4",
    poster: "/videos/posters/no-bgm-respati-ardi-1.jpg",
  },
  {
    id: "perihal-sampah",
    title: "PERIHAL SAMPAH",
    caption: "",
    meta: "1:26",
    orientation: "vertical",
    type: "local",
    src: "/videos/vertical/perihal-sampah.mp4",
    poster: "/videos/posters/perihal-sampah.jpg",
  },
  {
    id: "perihal-sawah",
    title: "PERIHAL SAWAH",
    caption: "",
    meta: "1:15",
    orientation: "vertical",
    type: "local",
    src: "/videos/vertical/perihal-sawah.mp4",
    poster: "/videos/posters/perihal-sawah.jpg",
  },
  {
    id: "present",
    title: "PRESENT",
    caption: "",
    meta: "0:38",
    orientation: "vertical",
    type: "local",
    src: "/videos/vertical/present.mp4",
    poster: "/videos/posters/present.jpg",
  },
  {
    id: "ra-4-walikota-multitalent",
    title: "RA 4 WALIKOTA MULTITALENT",
    caption: "",
    meta: "0:21",
    orientation: "vertical",
    type: "local",
    src: "/videos/vertical/ra-4-walikota-multitalent.mp4",
    poster: "/videos/posters/ra-4-walikota-multitalent.jpg",
  },
  {
    id: "ra-retret-rev3",
    title: "RA RETRET REV3",
    caption: "",
    meta: "1:09",
    orientation: "vertical",
    type: "local",
    src: "/videos/vertical/ra-retret-rev3.mp4",
    poster: "/videos/posters/ra-retret-rev3.jpg",
  },
  {
    id: "ra5-aspal-rev2",
    title: "RA5 ASPAL REV2",
    caption: "",
    meta: "0:59",
    orientation: "vertical",
    type: "local",
    src: "/videos/vertical/ra5-aspal-rev2.mp4",
    poster: "/videos/posters/ra5-aspal-rev2.jpg",
  },
  {
    id: "reels-official-apa-jadinya-kalo-engga-ada-rosalia-indah-rev-2",
    title: "REELS OFFICIAL - APA JADINYA KALO ENGGA ADA ROSALIA INDAH Rev 2",
    caption: "",
    meta: "0:56",
    orientation: "vertical",
    type: "local",
    src: "/videos/vertical/reels-official-apa-jadinya-kalo-engga-ada-rosalia-indah-rev-2.mp4",
    poster: "/videos/posters/reels-official-apa-jadinya-kalo-engga-ada-rosalia-indah-rev-2.jpg",
  },
  {
    id: "reels-official-captain-ready",
    title: "REELS OFFICIAL - CAPTAIN READY!",
    caption: "",
    meta: "0:28",
    orientation: "vertical",
    type: "local",
    src: "/videos/vertical/reels-official-captain-ready.mp4",
    poster: "/videos/posters/reels-official-captain-ready.jpg",
  },
  {
    id: "reels-official-menyembuhkan-luka-rev-2",
    title: "REELS OFFICIAL - MENYEMBUHKAN LUKA Rev 2",
    caption: "",
    meta: "0:34",
    orientation: "vertical",
    type: "local",
    src: "/videos/vertical/reels-official-menyembuhkan-luka-rev-2.mp4",
    poster: "/videos/posters/reels-official-menyembuhkan-luka-rev-2.jpg",
  },
  {
    id: "respati-ardi-03-psim-rev1",
    title: "Respati Ardi 03 PSIM REV1",
    caption: "",
    meta: "0:50",
    orientation: "vertical",
    type: "local",
    src: "/videos/vertical/respati-ardi-03-psim-rev1.mp4",
    poster: "/videos/posters/respati-ardi-03-psim-rev1.jpg",
  },
  {
    id: "segmen-bmx",
    title: "SEGMEN BMX",
    caption: "",
    meta: "0:52",
    orientation: "vertical",
    type: "local",
    src: "/videos/vertical/segmen-bmx.mp4",
    poster: "/videos/posters/segmen-bmx.jpg",
  },
  {
    id: "segmen-boxing",
    title: "SEGMEN BOXING",
    caption: "",
    meta: "1:51",
    orientation: "vertical",
    type: "local",
    src: "/videos/vertical/segmen-boxing.mp4",
    poster: "/videos/posters/segmen-boxing.jpg",
  },
  {
    id: "segmen-skate",
    title: "SEGMEN SKATE",
    caption: "",
    meta: "2:32",
    orientation: "vertical",
    type: "local",
    src: "/videos/vertical/segmen-skate.mp4",
    poster: "/videos/posters/segmen-skate.jpg",
  },
  {
    id: "smf-diskon-besar-besaran",
    title: "SMF DISKON BESAR BESARAN",
    caption: "",
    meta: "0:17",
    orientation: "vertical",
    type: "local",
    src: "/videos/vertical/smf-diskon-besar-besaran.mp4",
    poster: "/videos/posters/smf-diskon-besar-besaran.jpg",
  },
  {
    id: "tanya-jawab",
    title: "TANYA JAWAB",
    caption: "",
    meta: "0:58",
    orientation: "vertical",
    type: "local",
    src: "/videos/vertical/tanya-jawab.mp4",
    poster: "/videos/posters/tanya-jawab.jpg",
  },
  {
    id: "trailer",
    title: "TRAILER",
    caption: "",
    meta: "1:03",
    orientation: "vertical",
    type: "local",
    src: "/videos/vertical/trailer.mp4",
    poster: "/videos/posters/trailer.jpg",
  },
  {
    id: "video1",
    title: "Video 1",
    caption: "",
    meta: "0:21",
    orientation: "vertical",
    type: "local",
    src: "/videos/vertical/video1.mp4",
    poster: "/videos/posters/video1.jpg",
  },
  {
    id: "video2",
    title: "Video 2",
    caption: "",
    meta: "0:13",
    orientation: "vertical",
    type: "local",
    src: "/videos/vertical/video2.mp4",
    poster: "/videos/posters/video2.jpg",
  },
  {
    id: "video3",
    title: "Video 3",
    caption: "",
    meta: "0:09",
    orientation: "vertical",
    type: "local",
    src: "/videos/vertical/video3.mp4",
    poster: "/videos/posters/video3.jpg",
  },
  {
    id: "video4",
    title: "Video 4",
    caption: "",
    meta: "0:48",
    orientation: "vertical",
    type: "local",
    src: "/videos/vertical/video4.mp4",
    poster: "/videos/posters/video4.jpg",
  },
  {
    id: "video5",
    title: "Video 5",
    caption: "",
    meta: "0:55",
    orientation: "vertical",
    type: "local",
    src: "/videos/vertical/video5.mp4",
    poster: "/videos/posters/video5.jpg",
  },
  {
    id: "video6",
    title: "Video 6",
    caption: "",
    meta: "0:36",
    orientation: "vertical",
    type: "local",
    src: "/videos/vertical/video6.mp4",
    poster: "/videos/posters/video6.jpg",
  },
  {
    id: "video7",
    title: "Video 7",
    caption: "",
    meta: "0:19",
    orientation: "vertical",
    type: "local",
    src: "/videos/vertical/video7.mp4",
    poster: "/videos/posters/video7.jpg",
  },
  {
    id: "videio8",
    title: "Video 8",
    caption: "",
    meta: "0:37",
    orientation: "vertical",
    type: "local",
    src: "/videos/vertical/videio8.mp4",
    poster: "/videos/posters/videio8.jpg",
  },
];
